t5/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  
  # Route :new for tasks must be slightly different
  resources :tasks, except: [:index, :new]
  get 'task/new/:id', to: 'tasks#new', as: 'new-task'

  # Taskboard routes
  resources :taskboards
  post 'taskboards/load/:group', to: 'taskboards#indexLoadTaskboards', as: 'taskboards-load-group'
  get 'dismiss', to: 'taskboards#dismissModal', as: 'taskboards-dismiss'
  
  resources :taskboard_groups, except: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

t5/app/models/taskboard.rb
class Taskboard < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_many :taskboard_groups_taskboards
    has_many :taskboard_groups, through: :taskboard_groups_taskboards do
        def << (taskboardGroup)
            begin
                super taskboardGroup
                return true
            rescue => exception
                return false
            end
        end
    end
    
    validates_presence_of :name

    def save!
        begin
            super
            return true
        rescue => exception
            return false
        end
    end
end

t5/app/controllers/taskboards_controller.rb
class TaskboardsController < ApplicationController
  before_action :set_taskboard, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /taskboards
  # GET /taskboards.json
  def index
    @pageTitle = 'View Taskboards'
    @navbarTitle = 'Manage your taskboards'
    @mainTitle = 'Taskboards'

    @taskboards = Taskboard.all
    @task = Task.new
    @taskStates = TaskState.all
    
    @taskboardGroups = TaskboardGroup.all
  end

  # POST /taskboards/load
  # POST /taskboards/load.json
  def indexLoadTaskboards
    @taskboardGroupId = taskboard_group_params[:group]

    if @taskboardGroupId == '0'
      @taskboards = Taskboard.all
    else
      @taskboards = TaskboardGroup.find(@taskboardGroupId).taskboards.all
    end

    @action = 'show-taskboard-group'

    respond_to do |format|
      format.html { render :index }
      format.js { render :index }
    end
  end

  # GET /taskboards/dismiss
  # GET /taskboards/dismiss.json
  def dismissModal
    @action = 'dismiss-modal'
    respond_to do |format|
      format.js { render :index }
    end
  end
  
  

  # GET /taskboards/1
  # GET /taskboards/1.json
  def show
    @action = 'show-taskboard'
    
    respond_to do |format|
      format.js { render :index }
    end
  end

  # GET /taskboards/new
  def new
    @taskboard = Taskboard.new
    @taskboard_groups = TaskboardGroup.all
    @action = 'new-taskboard'

    respond_to do |format|
      format.js { render :index }
    end
  end

  # GET /taskboards/1/edit
  def edit
    @taskboard_groups = TaskboardGroup.all
    @action = 'edit-taskboard'

    respond_to do |format|
      format.js { render :index }
    end
  end

  # POST /taskboards
  # POST /taskboards.json
  def create
    @taskboard = Taskboard.new(taskboard_params)
    
    taskboard_groups_params.each { |group| 
      # First element of collection_select is always "" for some reason
      if group != ""
        @taskboard.taskboard_groups << TaskboardGroup.find_by(id: group)
      end
    }

    respond_to do |format|
      if @taskboard.save
        format.html { redirect_to taskboards_path, notice: "Taskboard '#{@taskboard.name}' was successfully created." }
      else
        format.html { redirect_to taskboards_path, alert: "Taskboard '#{@taskboard.name}' could not be created." }
      end
    end
  end

  # PATCH/PUT /taskboards/1
  # PATCH/PUT /taskboards/1.json
  def update
    oldName = @taskboard.name
    @taskboard.name = taskboard_params[:name]

    if taskboard_groups_params.length > 1
      @taskboard.taskboard_groups.delete_all

      taskboard_groups_params.each { |group| 
        # First element of collection_select is always "" for some reason
        if group != ""
          @taskboard.taskboard_groups << TaskboardGroup.find_by(id: group)
        end
      }
    end

    respond_to do |format|
      if @taskboard.save
        format.html { redirect_to taskboards_path, notice: "Taskboard '#{oldName}' was successfully updated." }
      else
        format.html { redirect_to taskboards_path, alert: "Taskboard '#{oldName}' could not be updated." }
      end
    end
  end

  # DELETE /taskboards/1
  # DELETE /taskboards/1.json
  def destroy
    @taskboard.destroy
    respond_to do |format|
      format.html { redirect_to taskboards_url, notice: 'Taskboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taskboard
      @taskboard = Taskboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taskboard_params
      params.require(:taskboard).permit(:name, :taskboard_group)
    end

    def taskboard_groups_params
      params.require(:taskboard_group).require(:id)
    end

    def taskboard_group_params
      params.permit(:group)
    end
end

t5/app/helpers/taskboards_helper.rb
module TaskboardsHelper
end

t5/app/views/taskboards/_form.html.erb
<%= form_with(model: @taskboard, local: true) do |form| %>
  <% if @taskboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taskboard.errors.count, "error") %> prohibited this taskboard from being saved:</h2>

      <ul>
      <% @taskboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :taskboard_groups %>
    <%= collection_select :taskboard_group, :id, @taskboard_groups, :id, :name, { prompt: false }, { multiple: true, size: 5 } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

t5/app/views/taskboards/_modal.html.erb
<div id="form-modal" style="display:none">
    <div class="darken animation-fade-in"></div>
    <div class="fs-a flex flex-hc flex-vc">
      <div class="modal animation-fade-in">
          <%= link_to raw('<i class="fas fa-times"></i>'), taskboards_dismiss_path, remote: true %>
          <div id="form-container"></div>
      </div>
    </div>
</div>

t5/app/views/taskboards/_show.html.erb
<% if current_user.isAdmin %>
  <%= link_to raw('<i class="fas fa-edit"></i>'), edit_taskboard_path(@taskboard), remote: true %>
  <%= link_to raw('<i class="fas fa-trash"></i>'), taskboard_path(@taskboard), method: :delete %>
<% end %>

<p>
  <strong class="🌹" title="Inspect me!">Name:</strong>
  <%= @taskboard.name %>
</p>

t5/app/views/taskboards/_taskboards.html.erb
<% @taskboards.each do |t| %>
<div class="taskboard">
    <% displayName = (t.name.length > 13 ? t.name[0,13] + '...' : t.name) %>
    <%= link_to raw("<h1 class=\"taskboard__title\">#{displayName}</h1>"), taskboard_path(t), remote: true %>
    
    <%= link_to raw('<i class="far fa-plus-square"></i>'), new_task_path(t.id), remote: true, id: :new %>
    
    <div class="taskboard__task-container">
        <% t.tasks.each do |task| %>
            <%= link_to task.name, task_path(task.id), remote: true, class: 'taskboard__task-container__task' %>
        <% end %>
    </div>
</div>
<% end %>

t5/app/views/taskboards/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag params[:controller] %>
<% end %>

<% content_for :js do %>
  <%= javascript_include_tag 'jquery.min.js' %>
  <%= javascript_include_tag params[:controller] %>
<% end %>

<% content_for :navbar_options do %>
  <% if current_user.isAdmin %>
    <%= link_to "New Taskboard", new_taskboard_path, remote: true %>
  <% end %>
<% end %>

<% content_for :aside do %>
  <aside class="left-aside">
    <div class="taskboard-groups-container">
      <h1 class="taskboard-groups-container__title">Taskboard Groups</h1>
      
      <% if current_user.isAdmin %>
        <%= link_to raw('<i class="far fa-plus-square"></i>'), new_taskboard_group_path, remote: true, id: :new %>
      <% end %>

      <ul id="taskboard-groups">
        <li>
          <%= button_to "ALL", taskboards_load_group_url(0), remote: true, method: :post %>
        </li>
        <% @taskboardGroups.each do |g| %>
          <li>
            <%= button_to g.name.length > 9 ? g.name[0,9] + '...' : g.name, taskboards_load_group_url(g.id), remote: true, method: :post %>

            <% if current_user.isAdmin %>
              <%= link_to raw('<i class="fas fa-edit"></i>'), edit_taskboard_group_path(g.id), remote: true, id: 'edit' %>
              <%= link_to raw('<i class="fas fa-trash"></i>'), taskboard_group_path(g.id), method: :delete, id: 'delete' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </aside>
<% end %>

<p id="alert"><%= alert %></p>
<p id="notice"><%= notice %></p>

<div id="taskboards-container"><%= render partial: 'taskboards/taskboards', locals: { taskboards: @taskboards } %></div>

<%= render 'modal' %>

t5/app/views/taskboards/index.js.erb
<% case @action

   when 'show-taskboard-group' %>
$("#taskboards-container").attr("data-group", "<%= @taskboardGroupId != '0' ? @taskboardGroupId : nil %>")
$("#taskboards-container").html("<%= j render(partial: 'taskboards') %>")

<% when 'edit-taskboard-group', 'new-taskboard-group' %>
taskboardManager.setForm("<%= j render(partial: 'taskboard_groups/form') %>")
taskboardManager.showModal()

<% when 'show-taskboard' %>
taskboardManager.setForm("<%= j render(partial: 'show') %>")
taskboardManager.showModal()

<% when 'edit-taskboard' %>
taskboardManager.setForm("<%= j render(partial: 'form') %>")

<% when 'new-taskboard' %>
taskboardManager.setForm("<%= j render(partial: 'form') %>")
taskboardManager.showModal()

<% when 'show-task'%>
taskboardManager.setForm("<%= j render(partial: 'tasks/show') %>")
taskboardManager.showModal()

<% when 'edit-task' %>
taskboardManager.setForm("<%= j render(partial: 'tasks/form') %>")

<% when 'new-task' %>
taskboardManager.setForm("<%= j render(partial: 'tasks/form') %>")
taskboardManager.showModal()

<% when 'dismiss-modal' %>
taskboardManager.hideModal()

<% else%>

<% end %>