t5/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  
  # Route :new for tasks must be slightly different
  resources :tasks, except: [:index, :new]
  get 'task/new/:id', to: 'tasks#new', as: 'new-task'

  # Taskboard routes
  resources :taskboards
  post 'taskboards/load/:group', to: 'taskboards#indexLoadTaskboards', as: 'taskboards-load-group'
  get 'dismiss', to: 'taskboards#dismissModal', as: 'taskboards-dismiss'
  
  resources :taskboard_groups, except: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

t5/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_state
  belongs_to :due_date, dependent: :destroy
  belongs_to :taskboard
  
  validates_presence_of :name
end

t5/app/controllers/tasks_controller.rb
require 'time'

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @action = 'show-task'

    respond_to do |format|
      format.js { render 'taskboards/index' }
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @taskStates = TaskState.all
    @taskboardId = params[:id]
    @action = 'new-task'

    respond_to do |format|
      format.js { render 'taskboards/index' }
    end
  end

  # GET /tasks/1/edit
  def edit
    @action = 'edit-task'
    @taskboardId = @task.taskboard.id
    @taskStates = TaskState.all

    respond_to do |format|
      format.js { render '/taskboards/index' }
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @taskboard = Taskboard.find_by(id: task_params[:taskboard_id])
    d = params[:due_date]
    @dueDate = DueDate.create date: "#{d['date(1i)']}-#{d['date(2i)']}-#{d['date(3i)']} #{d['date(4i)']}:#{d['date(5i)']}:00"
    @task = Task.create name: task_params[:name],
                        description: task_params[:description],
                        task_state_id: task_params[:task_state_id]
                        
    @task.due_date = @dueDate
    @task.taskboard = @taskboard
    
    @dueDate.task = @task
    @dueDate.save!
                        
    respond_to do |format|
      if @task.save
        format.html { redirect_to taskboards_path, notice: 'Task was successfully created.' }
      else
        format.html { redirect_to taskboards_path, notice: 'Task could not be created.' }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @dueDate = @task.due_date
    
    d = params[:due_date]
    
    @dueDate.date = "#{d['date(1i)']}-#{d['date(2i)']}-#{d['date(3i)']} #{d['date(4i)']}:#{d['date(5i)']}:00"
    
    @dueDate.save!
    
    taskName = @task.name
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to taskboards_path, notice: "Task '#{taskName}' was successfully updated." }
      else
        format.html { redirect_to taskboards_path, alert: "Task '#{taskName}' could not be updated." }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    taskName = @task.name
    @task.destroy
    
    respond_to do |format|
      format.html { redirect_to taskboards_path, notice: "Task '#{taskName}' was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :task_state_id, :due_date_id, :due_date, :taskboard_id)
    end
end

t5/app/helpers/tasks_helper.rb
module TasksHelper
end

t5/app/views/tasks/_edit.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag params[:controller] %>
<% end %>

<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task, remote: true %> |
<%= link_to 'Back', taskboards_dismiss_path, remote: true %>

t5/app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
    <% if @task.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    
    <input type="hidden" name="task[taskboard_id]" value="<%= @taskboardId %>"></input>
    
    <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>

    <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
    </div>

    <div class="field">
    <%= form.label :task_state_id %>
    <%= form.collection_select :task_state_id, @taskStates, :id, :name %>
    </div>

    <div class="field">
    <%= form.label :due_date %>
    <%= datetime_select :due_date, :date %>
    </div>

    <div class="actions">
    <%= form.submit %>
    </div>
<% end %>

t5/app/views/tasks/_show.html.erb
<%= link_to raw('<i class="fas fa-edit"></i>'), edit_task_path(@task), remote: true %>
<%= link_to raw('<i class="fas fa-trash"></i>'), task_path(@task), method: :delete %>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Task state:</strong>
  <%= @task.task_state.name %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date.date %>
</p>

<p>
  <strong>Taskboard:</strong>
  <%= @task.taskboard.name %>
</p>